### ISSUE TITLE
Workflows failing on 1.0.7 Cannot find module './664.index.js'

### ISSUE THREAD

**Issue by Kuuuube** [cardinalby/webext-buildtools-firefox-sign-xpi-action#9]
Error:

```
Error: Cannot find module './664.index.js'
```

Failed workflow:

https://github.com/themoeway/yomitan/actions/runs/8765698303/job/24057041389#step:3:13

Workflow file:

https://github.com/themoeway/yomitan/blob/94c0b943e84504629109d4852f4a080c6b0e569e/.github/workflows/publish-firefox-development.yml

Currently, we have reverted back to 1.0.6 to fix our workflows.

**Comment by cardinalby** [comment]
Hi! Sorry for breaking your pipeline :( 

Updated some dependencies and missed the newly appeared dist file

Pls. try 1.0.8 and let me know if it works for you

**Comment by Kuuuube** [comment]
Thank you for the quick fix! I can confirm it now works correctly.
